# let's analyze the csv files

In [22]:
import pandas as pd
df_1 = pd.read_csv(r"C:\Users\peter\OneDrive\Desktop\final_exam\interviews\incidenti_stradali_ultimi_5_anni.csv")
df_1.shape

(90144, 16)

In [23]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 90144 entries, 0 to 90143
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATAFLOW          90144 non-null  str
 1   FREQ              90144 non-null  str
 2   REF_AREA          90144 non-null  int64
 3   DATA_TYPE         90144 non-null  str
 4   RESULT            90144 non-null  str
 5   TIME_PERIOD       90144 non-null  int64
 6   OBS_VALUE         90144 non-null  int64
 7   OBS_STATUS        0 non-null      float64
 8   NOTE_DS           0 non-null      float64
 9   NOTE_REF_AREA     0 non-null      float64
 10  NOTE_DATA_TYPE    0 non-null      float64
 11  NOTE_RESULT       0 non-null      float64
 12  NOTE_TIME_PERIOD  0 non-null      float64
 13  BASE_PER          0 non-null      float64
 14  UNIT_MEAS         0 non-null      float64
 15  UNIT_MULT         0 non-null      float64
dtypes: float64(9), int64(3), str(4)
memory usage: 11.0 MB

In [24]:
df_1.sample(10)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
2775,IT1:41_983(1.0),A,1252,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,IT1:41_983(1.0),A,1081,KILLINJ,F,2021,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14835,IT1:41_983(1.0),A,12005,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50066,IT1:41_983(1.0),A,52018,ROADACC,9,2024,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,IT1:41_983(1.0),A,1057,KILLINJ,F,2024,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37318,IT1:41_983(1.0),A,26084,KILLINJ,M,2021,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58347,IT1:41_983(1.0),A,63025,ROADACC,9,2022,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64463,IT1:41_983(1.0),A,68040,KILLINJ,F,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82792,IT1:41_983(1.0),A,95052,ROADACC,9,2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26296,IT1:41_983(1.0),A,18053,KILLINJ,F,2022,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# after reviewing df_1, i begin cleaning it.

In [25]:
df_1.columns

Index(['DATAFLOW', 'FREQ', 'REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD',
       'OBS_VALUE', 'OBS_STATUS', 'NOTE_DS', 'NOTE_REF_AREA', 'NOTE_DATA_TYPE',
       'NOTE_RESULT', 'NOTE_TIME_PERIOD', 'BASE_PER', 'UNIT_MEAS',
       'UNIT_MULT'],
      dtype='str')

In [26]:
cars_accidents = df_1.copy()
cols_1 = ['DATAFLOW',
          'FREQ',
          'OBS_STATUS',
          'NOTE_DS',
          'NOTE_REF_AREA',
          'NOTE_DATA_TYPE',
          'NOTE_RESULT',
          'NOTE_TIME_PERIOD',
          'BASE_PER',
          'UNIT_MEAS',
          'UNIT_MULT']
cars_accidents.drop(columns=cols_1, inplace=True)
cars_accidents.shape

(90144, 5)

In [27]:
cars_accidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 90144 entries, 0 to 90143
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   REF_AREA     90144 non-null  int64
 1   DATA_TYPE    90144 non-null  str
 2   RESULT       90144 non-null  str
 3   TIME_PERIOD  90144 non-null  int64
 4   OBS_VALUE    90144 non-null  int64
dtypes: int64(3), str(2)
memory usage: 3.4 MB

In [28]:
cars_accidents.sample(10)

       REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
37313     26083   ROADACC      9         2024         51
41023     30111   KILLINJ      F         2022          0
8230       5014   KILLINJ      M         2021          1
16410     13005   ROADACC      9         2022          1
13182      9029   KILLINJ      M         2023          2
8110       5003   KILLINJ      M         2024          0
89188    111024   KILLINJ      F         2022          0
88809    110001   KILLINJ      M         2023          7
43065     35029   KILLINJ      F         2021         45
33151     23002   KILLINJ      M         2021          0

In [29]:
cars_accidents.rename(columns={'REF_AREA': 'id_code','DATA_TYPE':'type','RESULT':'outcome','TIME_PERIOD':'year','OBS_VALUE':'obs_value'}, inplace=True)
cars_accidents.head(10)

   id_code     type outcome  year  obs_value
0     1001  KILLINJ       F  2021          2
1     1001  KILLINJ       F  2022          5
2     1001  KILLINJ       F  2023          6
3     1001  KILLINJ       F  2024          5
4     1001  KILLINJ       M  2021          0
5     1001  KILLINJ       M  2022          0
6     1001  KILLINJ       M  2023          1
7     1001  KILLINJ       M  2024          0
8     1001  ROADACC       9  2021          2
9     1001  ROADACC       9  2022          3

In [30]:
cars_accidents

       id_code     type outcome  year  obs_value
0         1001  KILLINJ       F  2021          2
1         1001  KILLINJ       F  2022          5
2         1001  KILLINJ       F  2023          6
3         1001  KILLINJ       F  2024          5
4         1001  KILLINJ       M  2021          0
...        ...      ...     ...   ...        ...
90139   111107  KILLINJ       M  2024          0
90140   111107  ROADACC       9  2021          5
90141   111107  ROADACC       9  2022          1
90142   111107  ROADACC       9  2023          4
90143   111107  ROADACC       9  2024          3

[90144 rows x 5 columns]